config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :edit, :update]
  resources :order_items
  resources :orders do
    resources :comments, module: :orders
  end
  resources :carts, only: [:show, :destroy]
  resources :products do
    resources :comments, module: :products
  end
  resources :tags
  resources :likes, only: [:create, :destroy]
  root 'home#index', as: 'home_index'

  namespace :api do    
    namespace :v1 do
      resources :products, only: [:index, :show]
      resources :orders, only: [:index]
      resources :likes, only: [:create]
      post 'auth/login', to: 'authentication#login'
    end
  end

  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home controller class
class HomeController < ApplicationController
  include CurrentCart

  before_action :set_cart

  def index
    @pagy, @products = pagy(ProductsQuery.new.order(params[:sort]))
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Helpers for home
module HomeHelper
end

app/views/home/index.html.erb
<h1>Products</h1>


<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Sku</th>
      <th scope="col"><%= link_to 'Name', sort: 'name' %></th>
      <th scope="col">Description</th>
      <th scope="col"><%= link_to 'Price', sort: 'price' %></th>
      <th scope="col"><%= link_to 'Stock', sort: 'stock' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.sku %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= button_to 'Add to Cart', order_items_path(product_id: product) unless product.stock == 0 %>
      </tr>
    <% end %>
  </tbody>
</table>
<%== pagy_bootstrap_nav(@pagy) %>