config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :edit, :update]
  resources :order_items
  resources :orders do
    resources :comments, module: :orders
  end
  resources :carts, only: [:show, :destroy]
  resources :products do
    resources :comments, module: :products
  end
  resources :tags
  resources :likes, only: [:create, :destroy]
  root 'home#index', as: 'home_index'

  namespace :api do    
    namespace :v1 do
      resources :products, only: [:index, :show]
      resources :orders, only: [:index]
      resources :likes, only: [:create]
      post 'auth/login', to: 'authentication#login'
    end
  end

  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/order.rb
# frozen_string_literal: true

# Order model class
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  enum status: { processing: 0, completed: 1, canceled: 2, failed: 3 }
end

app/controllers/api/v1/orders_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Users controller class
    class OrdersController < ApplicationController
      before_action :authorize_request

      # GET /api/v1/orders
      def index
        @orders = OrdersQuery.new.user_orders(current_user)
        render json: OrderRepresenter.for_collection.new(@orders).to_json, status: :ok
      end
    end
  end
end

app/controllers/orders/comments_controller.rb
# frozen_string_literal: true

module Orders
  # Controller for comments of orders
  class CommentsController < CommentsController
    before_action :set_commentable

    private

    # Set the commentable object to the order
    def set_commentable
      @commentable = Order.find(params[:order_id])
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

# Order controller class
class OrdersController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: %i[new create]
  before_action :set_order, only: %i[show destroy]
  before_action :require_logged
  before_action :check_current_user, only: [:show]

  # GET /orders or /orders.json
  def index
    @pagy, @orders = pagy(OrdersQuery.new.user_orders(current_user))
  end

  # GET /orders/1 or /orders/1.json
  def show; end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # POST /orders or /orders.json
  def create
    @order = Order::Create.call(@cart, current_user)
    respond_to do |format|
      if @order.save
        Order::CreateLog.call(@order)
        Cart::Destroy.call(@cart, session)
        format.html { redirect_to home_index_url, notice: 'Order was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def require_logged
    return if user_signed_in?

    redirect_to new_user_registration_url, alert: 'Only logged users can buy products'
  end

  def check_current_user
    return if current_user.id == @order.user_id

    redirect_to home_index_url, alert: 'You don\'t have permisson to see that order'
  end
end

app/helpers/api/v1/order_helper.rb
module Api::V1::OrderHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

# Helpers for orders
module OrdersHelper
end

app/views/orders/index.html.erb
<h2 class="text-center">Orders</h2>

<div class="col-md-3">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Order ID</th>
        <th>Total</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= order.total %></td>
          <td><%= order.status %></td>
          <td><%= link_to 'Show', order %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/orders/new.html.erb
<h1>Order</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Name</th>
      <th>Unit Price</th>
      <th>Total Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart.order_items.each do |item| %>
      <tr>
        <td><%= item.quantity %></td>
        <td><%= item.product.name %></td>
        <td><%= number_to_currency(item.product.price) %></td>
        <td><%= number_to_currency(item.total_price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Total Price: <%= number_to_currency(@cart.total_price) %> </h3>

<%= button_to 'Confirm Buy', orders_path, method: :post %>

<%= link_to 'Back', home_index_path %>

app/views/orders/show.html.erb
<%= link_to 'Back', orders_path %>

<div class="col-md-3">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Product</th>
      <th>Unit Price</th>
    </tr>
  </thead>
  <tbody>
    <% @order.order_items.each do |ol| %>
      <tr>
        <td><%= ol.quantity %></td>
        <td><%= ol.product_name %></td>
        <td><%= ol.product_price %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<p>Total Price: <%= number_to_currency(@order.total) %></p>

<%= render partial: 'comments/comments', locals: {commentable: @order} %>
<%= render partial: 'comments/form', locals: {commentable: @order} %>