config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :edit, :update]
  resources :order_items
  resources :orders do
    resources :comments, module: :orders
  end
  resources :carts, only: [:show, :destroy]
  resources :products do
    resources :comments, module: :products
  end
  resources :tags
  resources :likes, only: [:create, :destroy]
  root 'home#index', as: 'home_index'

  namespace :api do    
    namespace :v1 do
      resources :products, only: [:index, :show]
      resources :orders, only: [:index]
      resources :likes, only: [:create]
      post 'auth/login', to: 'authentication#login'
    end
  end

  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/tag.rb
# frozen_string_literal: true

# Tag model class
class Tag < ApplicationRecord
  has_and_belongs_to_many :products, dependent: :nil

  validates :name, presence: true
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

# Products controller class
class TagsController < ApplicationController
  before_action :set_tag, only: %i[show destroy]

  def index
    @tags = Tag.all
  end

  def show; end

  def new
    @tag_form = Tag::CreateForm.new
  end

  def edit
    @tag_edit_form = Tag::EditForm.new('id' => params[:id])
  end

  def create
    @tag_form = Tag::CreateForm.new(tag_params)
    @tag = Tag::Create.call(@tag_form.submit)
    if @tag
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @tag_edit_form = Tag::EditForm.new(tag_edit_params.merge(id: params[:id]))
    @tag = Tag::Update.call(@tag_edit_form.submit)
    if @tag
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
    end
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag_create_form).permit(:name)
  end

  def tag_edit_params
    params.require(:tag_edit_form).permit(:name)
  end
end

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>

<%= form_for @tag_edit_form, url: tag_path(@tag_edit_form.id), method: 'put' do |form| %>
  <% if @tag_edit_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag_edit_form.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% @tag_edit_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Edit tag' %>
  </div>
<% end %>

<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= form_for @tag_form, url: tags_path do |form| %>
  <% if @tag_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag_form.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% @tag_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Tag' %>
  </div>
<% end %>


<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>