config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :edit, :update]
  resources :order_items
  resources :orders do
    resources :comments, module: :orders
  end
  resources :carts, only: [:show, :destroy]
  resources :products do
    resources :comments, module: :products
  end
  resources :tags
  resources :likes, only: [:create, :destroy]
  root 'home#index', as: 'home_index'

  namespace :api do    
    namespace :v1 do
      resources :products, only: [:index, :show]
      resources :orders, only: [:index]
      resources :likes, only: [:create]
      post 'auth/login', to: 'authentication#login'
    end
  end

  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/product.rb
# frozen_string_literal: true

# Product model class.
# Represents the items that the store sells
class Product < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant resize_to_limit: [220, 220]
  end
  has_many :order_items, dependent: :nullify
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_and_belongs_to_many :tags, dependent: :nil

  validates :name, :sku, presence: true
  validates :sku, uniqueness: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :stock, numericality: { greater_than_or_equal_to: 0 }

  # Returns true if there is an admin logged in
  # Receives a +user+ as parameter
  def editable_by?(current_user)
    !!current_user && (current_user.admin? || current_user.support?)
  end
end

app/controllers/api/v1/products_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Products controller class
    class ProductsController < ApplicationController
      # GET api/products
      def index
        @products = ProductsQuery.new.order(params[:sort])
        render json: ProductRepresenter.for_collection.new(@products).to_json, status: :ok
      end

      # GET api/products/1
      def show
        @product = Product::Find.call(params[:id])
        render json: ProductRepresenter.new(@product).to_json, status: :ok
      end
    end
  end
end

app/controllers/products/comments_controller.rb
# frozen_string_literal: true

module Products
  # Controller for comments of products
  class CommentsController < CommentsController
    before_action :set_commentable

    private

    # Set the commentable object to the order
    def set_commentable
      @commentable = Product.find(params[:product_id])
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Products controller class
class ProductsController < ApplicationController
  include SecureRolePermissions

  before_action :set_product, only: %i[show edit update destroy]
  before_action :require_support, except: [:show]

  # GET /products or /products.json
  def index
    @pagy, @products = pagy(Product.all)
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product_form = Product::CreateForm.new
  end

  # GET /products/1/edit
  def edit
    @product_edit_form = Product::EditForm.new(id: params[:id])
  end

  # POST /products or /products.json
  def create
    @product_form = Product::CreateForm.new(product_params)
    @product = Product::Create.call(@product_form.submit)

    if @product
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product_edit_form = Product::EditForm.new(product_edit_params.merge(id: params[:id]))
    @product = Product::Update.call(@product_edit_form.submit)
    if @product
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product_create_form).permit(:sku, :name, :description, :image, :price, :stock, tag_ids: [])
  end

  def product_edit_params
    params.require(:product_edit_form).permit(:sku, :name, :description, :image, :price, :stock, tag_ids: [])
  end
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

# Helpers for products
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= form_for @product_edit_form, url: product_path(@product_edit_form.id), method: 'put', html: { class: 'w-50 '} do |form| %>
  <% if @product_edit_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_edit_form.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product_edit_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :sku %>
    <%= form.text_field :sku, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :stock %>
    <%= form.number_field :stock, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image , class: 'form-control'%>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Sku</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Price</th>
      <th scope="col">Stock</th>
      <th scope="col">Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.sku %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= product.stock %></td>
        <td>
          <% product.tags.each do |tag| %>
            <%= tag.name %> |
          <% end %>
        </td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%== pagy_nav(@pagy) %>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_for @product_form, url: products_path, html: { class: 'w-50 '} do |form| %>
  <% if @product_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_form.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :sku %>
    <%= form.text_field :sku, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :stock %>
    <%= form.number_field :stock, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image , class: 'form-control'%>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<% if @product.image.representable? %>
  <%= image_tag @product.image.representation(resize_to_limit: [220, 220]) %>
<% end %>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Tags:</strong>
  <% @product.tags.each do |tag| %>
    <%= tag.name %> |
  <% end %>
</p>

<p><strong> Likes: <%= @product.likes.count %></strong></p>
<% if user_signed_in? %>
  <% like = current_user.likes.find_by(product: @product) %>
  <% if like.nil? %>
    <%= button_to 'Like', likes_path, params: { like: { product_id: @product.id }}, method: :post %>
  <% else %>
    <%= button_to 'Unlike', like_path(like), method: :delete %>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_product_path(@product) if @product.editable_by?(current_user) %> |
<%= link_to 'Back', products_path %>

<%= render partial: 'comments/comments', locals: {commentable: @product} %>
<%= render partial: 'comments/form', locals: {commentable: @product} %>